const MOVIES = ["The Exorcist",
"The Sword of Doom",
"Rabid",
"What Lies Beneath",
"Dogtooth",
"Westworld",
"The Salvation",
"Black Rain",
"Look Who's Back",
"The Descent",
"Rumble Fish",
"Slacker",
"The House with a Clock in Its Walls",
"Tombstone",
"Lawrence of Arabia",
"The Omen",
"Oldboy",
"Stockholm",
"District 9",
"The Color of Pomegranates",
"Batman: Mask of the Phantasm",
"Lady Snowblood",
"No Country for Old Men",
"Trick 'r Treat",
"Citizen Kane",
"Tokyo Story",
"Journey to Italy",
"Primer",
"Seven Samurai",
"La Haine",
"Magnolia",
"I Saw the Devil",
"Border",
"Vivre Sa Vie",
"Fantastic Mr. Fox",
"Snowpiercer",
"Groundhog Day",
"Uncut Gems",
"Knives Out",
"The Thing", 
"The Farewell",
"It's a Wonderful Life",
"Frances Ha",
"Waves",
"Singin' in the Rain",
"Metropolis",
"Swiss Army Man",
"Bullitt",
"Ferris Bueller's Day Off",
"Django Unchained",
"Pain and Glory",
"The Wicker Man",
"Lady Bird",
"The Thin Red Line",
"Revolver",
"The People vs. Larry Flynt",
"There Will Be Blood",
"Heavy Trip",
"Joint Security Area",
"Amadeus"]

exports.movies = MOVIES