const MOVIES =
    ["The Exorcist",
        "The Sword of Doom",
        "Rabid",
        "Westworld",
        "The Salvation",
        "Black Rain",
        "Look Who's Back",
        "The Descent",
        "Rumble Fish",
        "Slacker",
        "Tombstone",
        "The Omen",
        "Oldboy",
        "Stockholm",
        "District 9",
        "The Color of Pomegranates",
        "Lady Snowblood",
        "Le samourai",
        "Trick 'r Treat",
        "Citizen Kane",
        "Tokyo Story",
        "Journey to Italy",
        "Seven Samurai",
        "La Haine",
        "Magnolia",
        "Border",
        "Vivre Sa Vie",
        "Fantastic Mr. Fox",
        "In the mood for love",
        "Drive",
        "Do the right thing",
        "The Thing",
        "The Farewell",
        "It's a Wonderful Life",
        "Frances Ha",
        "Singin' in the Rain",
        "Metropolis",
        "Swiss Army Man",
        "Bullitt",
        "Django Unchained",
        "Pain and Glory",
        "The Wicker Man",
        "Lady Bird",
        "Heavy Trip",
        "Joint Security Area",
        "Amadeus",
        "Into the Wild",
        "Schindler's List",
        "Man of Tai Chi",
        "Love Me If You Dare",
        "Green Book",
        "Neruda",
        "Rope",
        "The Rebel",
        "A Better Tomorrow",
        "Rhino Season",
        "Hesher",
        "The Boat That Rocked",
        "Parasite",
        "Fargo",
        "House of Wax",
        "The Witch",
        "Emma.",
        "Yi Yi",
        "The Iron Giant",
        "An Elephant Sitting Still",
        "The Traitor",
        "Gummo",
        "Candy",
        "Elephant",
        "Tangerine",
        "When Harry Met Sally...",
        "Saving Private Ryan",
        "Cracks",
        "Atonement"
    ]


exports.movies = MOVIES
