
const MOVIES =
    ["The Exorcist",
    "The Sword of Doom",
    "Rabid",
    "Westworld",
    "The Salvation",
    "Black Rain",
    "Look Who's Back",
    "The Descent",
    "Rumble Fish",
    "Slacker",
    "Tombstone",
    "The Omen",
    "Oldboy",
    "Stockholm",
    "District 9",
    "The Color of Pomegranates",
    "Lady Snowblood",
    "Trick 'r Treat",
    "Citizen Kane",
    "Tokyo Story",
    "Seven Samurai",
    "La Haine",
    "I Saw the Devil",
    "Border",
    "Vivre Sa Vie",
    "Fantastic Mr. Fox",
    "The Thing",
    "It's a Wonderful Life",
    "Frances Ha",
    "Metropolis",
    "Swiss Army Man",
    "Bullitt",
    "Django Unchained",
    "Pain and Glory",
    "The Wicker Man",
    "Lady Bird",
    "Heavy Trip",
    "Joint Security Area",
    "Amadeus",
    "Into the Wild",
    "Schindler's List",
    "Man of Tai Chi",
    "Love Me If You Dare",
    "Green Book",
    "Neruda",
    "Rope",
    "The Rebel",
    "A Better Tomorrow",
    "Rhino Season",
    "Hesher",
    "The Boat That Rocked",
    "Parasite",
    "Fargo",
    "The Witch",
    "Emma.",
    "Yi Yi",
    "The Iron Giant",
    "An Elephant Sitting Still",
    "The Traitor",
    "Gummo",
    "Candy",
    "Elephant",
    "Tangerine",
    "When Harry Met Sally...",
    "Saving Private Ryan",
    "Cracks",
    "Atonement",
    "Do the Right Thing",
    "Le Samouraï",
    "Drive",
    "In the Mood for Love",
    "House of Wax",
    "Brazil",
    "Punch-Drunk Love",
    "You Were Never Really Here",
    "A Fish Called Wanda",
    "Ghost Dog: The Way of the Samurai",
    "A Bittersweet Life",
    "Memories of Murder",
    "Au Hasard Balthazar",
    "Outrage",
    "Loveless",
    "PK",
    "Paris"    
    ]


exports.movies = MOVIES
